### ISSUE TITLE
[Feature request] Update to 3.1.0 release 

### ISSUE THREAD

**Issue by einhander** [qutebrowser/qutebrowser-debian#3]
Please update to 3.1.0 release

**Comment by fiete201** [comment]
Hi,

thanks for creating this issue. I'm currently working on the debian
package for the 3.1.0 release.
I hope to finish it during the next weeks.

Best regards
Fritz
--

**Comment by toofar** [comment]
@fiete201 thank you for looking into this! I'm happy to see some recent commits toward making this available. Please let me know if there's anything I can do to help, I use debian myself so I can probably help with some stuff, although I've never delved into packaging.

**Comment by fiete201** [comment]
Hi toofar,

thanks for your offer to support. Currently the 3.0.0 release is in
review by my debian mentor. There is nothing we can do to speed this
up. They work as fast as their time allows.

But if I need some testers I will let you know!
In the meantime you can tinker with these .debs if you want

Frit
z
--

**Comment by fiete201** [comment]
https://tracker.debian.org/news/1550243/qutebrowser-310-1-migrated-to-testing/
qutebrowser 3.1.0 is in testing now.
3.2.1 is in the pipeline and waiting for review and sponsor upload
